# Generated by Django 5.2.7 on 2025-10-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0002_team_teammember"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_team_user"
            ),
        ),
    ]
