# Generated by Django 5.2.7 on 2025-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0004_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
