# Generated by Django 5.2.7 on 2025-10-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0005_document_content_type_document_size"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
