# Generated by Django 5.2.7 on 2025-10-21 16:15

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0006_add_pgvector_extension_to_db"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="intune.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
            },
        ),
    ]
