# Generated by Django 5.2.7 on 2025-10-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0009_chat_chatconversation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Conversation",
        ),
    ]
