# Generated by Django 5.2.7 on 2025-10-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0010_delete_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_conversation_active",
            field=models.BooleanField(default=False),
        ),
    ]
