# Generated by Django 5.2.7 on 2025-10-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intune", "0011_chat_is_conversation_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        ),
    ]
